-- Cocktail-name canonical seed.
-- Per the dedup spec, hand-seed the top ~100-200 well-known cocktails into
-- `cocktail_aliases` so the normalize-names Phase 1 alias layer can resolve
-- them without LLM. The alias text is the *normalized* form produced by
-- `normalize_cocktail_name` (lowercase, parentheticals dropped, punctuation
-- stripped, stop-words "the/a/an/best/perfect/classic/cocktail/recipe"
-- removed). Multiple aliases can point at the same canonical_name to
-- handle distinct normalized forms (diacritic variants, common
-- misspellings, alternate punctuation).
--
-- Canonical names: title case, matching how the cocktail community writes
-- the name on a menu (Negroni, Old Fashioned, Pimm's Cup, Piña Colada).
--
-- Priority list derived empirically from the dev-DB recipe corpus
-- (top normalized-name frequency among 20,427 scraped recipes). Variants
-- like "White Negroni" / "Negroni Sbagliato" / "Mango Margarita" / "Spicy
-- Margarita" / "Hemingway Daiquiri" stay as separate canonical names —
-- they're functionally different drinks even though they share a base.
--
-- Source: 'seed' marks every row added by hand here. The mapper marks
-- LLM-resolved rows 'llm' and operator-added rows 'manual' per the
-- check-constraint in migration `20260429160500_create_cocktail_aliases.sql`.

insert into cocktail_aliases (alias, canonical_name, source) values
  -- Tier 1: classics with highest corpus frequency.
  ('manhattan',              'Manhattan',              'seed'),
  ('mojito',                 'Mojito',                 'seed'),
  ('bloody mary',            'Bloody Mary',            'seed'),
  ('mint julep',             'Mint Julep',             'seed'),
  ('french 75',              'French 75',              'seed'),
  ('caipirinha',             'Caipirinha',             'seed'),
  ('margarita',              'Margarita',              'seed'),
  ('margarita with fresh lime juice', 'Margarita',     'seed'),
  ('sazerac',                'Sazerac',                'seed'),
  ('negroni',                'Negroni',                'seed'),
  ('pisco sour',             'Pisco Sour',             'seed'),
  ('daiquiri',               'Daiquiri',               'seed'),
  ('daquiri',                'Daiquiri',               'seed'),  -- common misspelling
  ('cosmopolitan',           'Cosmopolitan',           'seed'),
  ('cosmo',                  'Cosmopolitan',           'seed'),
  ('cosmopolitan cosmo',     'Cosmopolitan',           'seed'),  -- title with both forms
  ('whiskey sour',           'Whiskey Sour',           'seed'),
  ('whisky sour',            'Whiskey Sour',           'seed'),
  ('mai tai',                'Mai Tai',                'seed'),
  ('espresso martini',       'Espresso Martini',       'seed'),
  ('martini',                'Martini',                'seed'),
  ('hot toddy',              'Hot Toddy',              'seed'),
  ('moscow mule',            'Moscow Mule',            'seed'),
  ('hurricane',              'Hurricane',              'seed'),
  ('hot buttered rum',       'Hot Buttered Rum',       'seed'),
  ('eggnog',                 'Eggnog',                 'seed'),
  ('egg nog',                'Eggnog',                 'seed'),
  ('sidecar',                'Sidecar',                'seed'),
  -- "Cocktail" is a stop-word so "Champagne Cocktail" normalizes to just
  -- "champagne". Accept the false-positive risk for plain "Champagne"
  -- titles — in a cocktail-recipe corpus those are nearly always the
  -- canonical drink, not wine recommendations.
  ('champagne',              'Champagne Cocktail',     'seed'),
  ('white russian',          'White Russian',          'seed'),
  ('black russian',          'Black Russian',          'seed'),
  ('paloma',                 'Paloma',                 'seed'),
  ('new york sour',          'New York Sour',          'seed'),
  ('old fashioned',          'Old Fashioned',          'seed'),
  ('hemingway daiquiri',     'Hemingway Daiquiri',     'seed'),
  ('papa doble',             'Hemingway Daiquiri',     'seed'),  -- alternate name
  ('boulevardier',           'Boulevardier',           'seed'),
  ('martinez',               'Martinez',               'seed'),
  ('gimlet',                 'Gimlet',                 'seed'),
  ('bamboo',                 'Bamboo',                 'seed'),
  ('michelada',              'Michelada',              'seed'),
  ('long island iced tea',   'Long Island Iced Tea',   'seed'),
  ('americano',              'Americano',              'seed'),
  ('aviation',               'Aviation',               'seed'),
  ('singapore sling',        'Singapore Sling',        'seed'),
  ('rob roy',                'Rob Roy',                'seed'),
  ('dark and stormy',        'Dark and Stormy',        'seed'),
  ('dark n stormy',          'Dark and Stormy',        'seed'),
  ('dark stormy',            'Dark and Stormy',        'seed'),
  ('pimm s cup',             'Pimm''s Cup',            'seed'),  -- apostrophe normalizes to space
  ('pimms cup',              'Pimm''s Cup',            'seed'),
  ('white negroni',          'White Negroni',          'seed'),
  ('irish coffee',           'Irish Coffee',           'seed'),
  ('pink lady',              'Pink Lady',              'seed'),
  ('negroni sbagliato',      'Negroni Sbagliato',      'seed'),
  ('strawberry daiquiri',    'Strawberry Daiquiri',    'seed'),
  ('gold rush',              'Gold Rush',              'seed'),
  ('gin rickey',             'Gin Rickey',             'seed'),
  ('brooklyn',               'Brooklyn',               'seed'),
  ('aperol spritz',          'Aperol Spritz',          'seed'),
  ('brandy alexander',       'Brandy Alexander',       'seed'),
  ('amaretto sour',          'Amaretto Sour',          'seed'),
  ('mango margarita',        'Mango Margarita',        'seed'),
  ('tom collins',            'Tom Collins',            'seed'),
  ('turf club',              'Turf Club',              'seed'),
  ('vesper',                 'Vesper',                 'seed'),
  ('vesper martini',         'Vesper',                 'seed'),
  ('ramos gin fizz',         'Ramos Gin Fizz',         'seed'),
  ('penicillin',             'Penicillin',             'seed'),
  ('sherry cobbler',         'Sherry Cobbler',         'seed'),
  ('kir royale',             'Kir Royale',             'seed'),
  ('kir',                    'Kir',                    'seed'),
  ('paper plane',            'Paper Plane',            'seed'),
  ('painkiller',             'Painkiller',             'seed'),
  ('grasshopper',            'Grasshopper',            'seed'),
  ('bijou',                  'Bijou',                  'seed'),
  -- Tier 2: classics + neoclassics with medium frequency.
  ('el presidente',          'El Presidente',          'seed'),
  ('mimosa',                 'Mimosa',                 'seed'),
  ('rusty nail',             'Rusty Nail',             'seed'),
  ('piña colada',            'Piña Colada',            'seed'),
  ('pina colada',            'Piña Colada',            'seed'),  -- ASCII variant
  ('last word',              'Last Word',              'seed'),
  ('corpse reviver no 2',    'Corpse Reviver No. 2',   'seed'),
  ('corpse reviver 2',       'Corpse Reviver No. 2',   'seed'),
  ('corpse reviver number 2','Corpse Reviver No. 2',   'seed'),
  ('chocolate martini',      'Chocolate Martini',      'seed'),
  ('dirty martini',          'Dirty Martini',          'seed'),
  ('bellini',                'Bellini',                'seed'),
  ('lychee martini',         'Lychee Martini',         'seed'),
  ('bobby burns',            'Bobby Burns',            'seed'),
  ('vieux carré',            'Vieux Carré',            'seed'),
  ('vieux carre',            'Vieux Carré',            'seed'),  -- ASCII variant
  ('white lady',             'White Lady',             'seed'),
  ('jack rose',              'Jack Rose',              'seed'),
  ('jungle bird',            'Jungle Bird',            'seed'),
  ('coquito',                'Coquito',                'seed'),
  ('old pal',                'Old Pal',                'seed'),
  ('alaska',                 'Alaska',                 'seed'),
  ('clover club',            'Clover Club',            'seed'),
  ('gin basil smash',        'Gin Basil Smash',        'seed'),
  ('basil smash',            'Gin Basil Smash',        'seed'),
  ('banana daiquiri',        'Banana Daiquiri',        'seed'),
  ('french martini',         'French Martini',         'seed'),
  ('planter s punch',        'Planter''s Punch',       'seed'),
  ('planters punch',         'Planter''s Punch',       'seed'),
  ('hanky panky',            'Hanky Panky',            'seed'),
  ('chrysanthemum',          'Chrysanthemum',          'seed'),
  ('milk punch',             'Milk Punch',             'seed'),
  ('pegu club',              'Pegu Club',              'seed'),
  ('old cuban',              'Old Cuban',              'seed'),
  ('tequila sunrise',        'Tequila Sunrise',        'seed'),
  ('red hook',               'Red Hook',               'seed'),
  ('satan s whiskers',       'Satan''s Whiskers',      'seed'),
  ('satans whiskers',        'Satan''s Whiskers',      'seed'),
  ('southside',              'Southside',              'seed'),
  ('bronx',                  'Bronx',                  'seed'),
  ('black manhattan',        'Black Manhattan',        'seed'),
  ('ranch water',            'Ranch Water',            'seed'),
  ('siesta',                 'Siesta',                 'seed'),
  ('pink squirrel',          'Pink Squirrel',          'seed'),
  ('greyhound',              'Greyhound',              'seed'),
  ('bramble',                'Bramble',                'seed'),
  ('shirley temple',         'Shirley Temple',         'seed'),
  ('spicy margarita',        'Spicy Margarita',        'seed'),
  ('blood and sand',         'Blood and Sand',         'seed'),
  ('adonis',                 'Adonis',                 'seed'),
  ('breakfast martini',      'Breakfast Martini',      'seed'),
  ('appletini',              'Appletini',              'seed'),
  ('apple martini',          'Appletini',              'seed'),  -- functionally the same drink
  ('pisco punch',            'Pisco Punch',            'seed'),
  ('coconut margarita',      'Coconut Margarita',      'seed'),
  ('gin daisy',              'Gin Daisy',              'seed'),
  ('gin and tonic',          'Gin and Tonic',          'seed'),
  ('gin tonic',              'Gin and Tonic',          'seed'),
  ('g and t',                'Gin and Tonic',          'seed'),
  ('ti punch',               'Ti'' Punch',             'seed'),
  ('toronto',                'Toronto',                'seed'),
  ('tuxedo no 2',            'Tuxedo No. 2',           'seed'),
  ('tuxedo 2',               'Tuxedo No. 2',           'seed'),
  ('death in afternoon',     'Death in the Afternoon', 'seed'),  -- "the" is a stopword
  ('salty dog',              'Salty Dog',              'seed'),
  ('roman holiday',          'Roman Holiday',          'seed'),
  ('watermelon mojito',      'Watermelon Mojito',      'seed'),
  ('zombie',                 'Zombie',                 'seed'),
  ('seelbach',               'Seelbach',               'seed'),
  ('stone fence',            'Stone Fence',            'seed'),
  ('pineapple daiquiri',     'Pineapple Daiquiri',     'seed'),
  ('remember maine',         'Remember the Maine',     'seed'),  -- "the" stripped
  ('jasmine',                'Jasmine',                'seed'),
  ('saturn',                 'Saturn',                 'seed'),
  ('mexican martini',        'Mexican Martini',        'seed'),
  ('whiskey smash',          'Whiskey Smash',          'seed'),
  ('frozen margarita',       'Frozen Margarita',       'seed'),
  ('godfather',              'Godfather',              'seed'),
  ('carajillo',              'Carajillo',              'seed'),
  ('gibson',                 'Gibson',                 'seed'),
  ('lemon drop martini',     'Lemon Drop Martini',     'seed'),
  ('lemon drop',             'Lemon Drop Martini',     'seed'),
  ('algonquin',              'Algonquin',              'seed'),
  ('brandy crusta',          'Brandy Crusta',          'seed'),
  ('screwdriver',            'Screwdriver',            'seed'),
  ('brandy milk punch',      'Brandy Milk Punch',      'seed'),
  ('brown derby',            'Brown Derby',            'seed'),
  ('el diablo',              'El Diablo',              'seed'),
  ('oaxaca old fashioned',   'Oaxaca Old Fashioned',   'seed'),
  ('cuba libre',             'Cuba Libre',             'seed'),
  ('campari spritz',         'Campari Spritz',         'seed'),
  ('frozen negroni',         'Frozen Negroni',         'seed'),
  ('gin gin mule',           'Gin-Gin Mule',           'seed'),
  ('bloody maria',           'Bloody Maria',           'seed'),
  ('income tax',             'Income Tax',             'seed'),
  ('blinker',                'Blinker',                'seed'),
  ('rum swizzle',            'Rum Swizzle',            'seed'),
  ('blue hawaiian',          'Blue Hawaiian',          'seed'),
  ('harvey wallbanger',      'Harvey Wallbanger',      'seed'),
  -- Tier 3: completing the freq>=5 head and adding a few absolute classics
  -- not yet in the corpus's top slice.
  ('rum old fashioned',      'Rum Old Fashioned',      'seed'),
  ('tomato martini',          'Tomato Martini',         'seed'),
  ('tommy s margarita',       'Tommy''s Margarita',     'seed'),
  ('tommys margarita',        'Tommy''s Margarita',     'seed'),
  ('left hand',               'Left Hand',              'seed'),
  ('french connection',       'French Connection',      'seed'),
  ('stinger',                 'Stinger',                'seed'),
  ('revolver',                'Revolver',               'seed'),
  ('club',                    'Club Cocktail',          'seed'),  -- "Cocktail" stopword stripped
  ('club cocktail',           'Club Cocktail',          'seed'),
  ('sex on beach',            'Sex on the Beach',       'seed'),  -- "the" stopword
  ('suffering bastard',       'Suffering Bastard',      'seed'),
  ('sea breeze',              'Sea Breeze',             'seed'),
  ('bloody bull',             'Bloody Bull',            'seed'),
  ('sloe gin fizz',           'Sloe Gin Fizz',          'seed'),
  ('maple old fashioned',     'Maple Old Fashioned',    'seed'),
  ('pan american clipper',    'Pan American Clipper',   'seed'),
  ('fish house punch',        'Fish House Punch',       'seed'),
  ('bee s knees',             'Bee''s Knees',           'seed'),
  ('bees knees',              'Bee''s Knees',           'seed'),
  ('trinidad sour',           'Trinidad Sour',          'seed'),
  ('kentucky buck',           'Kentucky Buck',          'seed'),
  ('cable car',               'Cable Car',              'seed'),
  ('prescription julep',      'Prescription Julep',     'seed'),
  ('vodka martini',           'Vodka Martini',          'seed'),
  -- A few corpus drinks that aren't strictly cocktails but cluster usefully.
  ('red wine sangria',        'Red Wine Sangria',       'seed'),
  ('white sangria',           'White Sangria',          'seed'),
  ('red sangria',             'Red Sangria',            'seed'),
  ('rose sangria',            'Rosé Sangria',           'seed'),
  ('rosé sangria',            'Rosé Sangria',           'seed'),
  ('sangria',                 'Sangria',                'seed'),
  ('sangrita',                'Sangrita',               'seed'),
  ('rum punch',               'Rum Punch',              'seed'),
  ('champagne punch',         'Champagne Punch',        'seed'),
  ('mulled wine',             'Mulled Wine',            'seed'),
  ('mulled cider',             'Mulled Cider',          'seed'),
  ('limoncello',              'Limoncello',             'seed'),
  ('limeade',                 'Limeade',                'seed'),
  ('strawberry lemonade',     'Strawberry Lemonade',    'seed'),
  ('raspberry lemonade',      'Raspberry Lemonade',     'seed'),
  ('old fashioned lemonade',  'Old-Fashioned Lemonade', 'seed'),
  ('mango lassi',             'Mango Lassi',            'seed'),
  ('thai iced tea',           'Thai Iced Tea',          'seed'),
  ('cha yen',                 'Thai Iced Tea',          'seed'),  -- Thai name
  ('watermelon limeade',      'Watermelon Limeade',     'seed'),
  ('watermelon margarita',    'Watermelon Margarita',   'seed'),
  ('frozen mango margarita',  'Frozen Mango Margarita', 'seed'),
  ('gingerbread martini',     'Gingerbread Martini',    'seed'),
  ('dirty shirley',           'Dirty Shirley',          'seed'),
  ('black velvet',            'Black Velvet',           'seed'),
  -- Absolute classics worth seeding even where corpus shows fewer hits.
  ('mary pickford',           'Mary Pickford',          'seed'),
  ('aperitivo',               'Americano',              'seed')  -- "Americano" is the IBA aperitivo
on conflict (alias, canonical_name) do nothing;
