sites:
  - name: diffordsguide
    domain: diffordsguide.com
    url_pattern: "/cocktails/recipe/"
    sitemap_url: https://www.diffordsguide.com/sitemap.xml

  - name: liquor
    domain: liquor.com
    url_pattern: "/recipes/"
    sitemap_url: https://www.liquor.com/sitemap.xml
